-- Phase VII Step 2: Create Audit Log Table for Employee Actions
-- This captures all DML attempts on restricted tables
CREATE TABLE employee_action_audit (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_time DATE DEFAULT SYSDATE NOT NULL,
    username VARCHAR2(100) NOT NULL,
    action_type VARCHAR2(20) NOT NULL,
    table_name VARCHAR2(100) NOT NULL,
    action_status VARCHAR2(20) NOT NULL,
    error_message VARCHAR2(4000),
    session_info VARCHAR2(500)
);

COMMIT;

SELECT * FROM employee_action_audit;

SELECT table_name FROM user_tables WHERE table_name IN ('PUBLIC_HOLIDAYS', 'EMPLOYEE_ACTION_AUDIT') ORDER BY table_name;