-- Phase IV: Database Creation Script

CREATE PLUGGABLE DATABASE mon_27976_denyse_ertriage_db
  ADMIN USER DENYSE_ADMIN IDENTIFIED BY "Denyse"
  ROLES = (DBA)
FILE_NAME_CONVERT = (
  'C:\APP\DELL\PRODUCT\21C\ORADATA\XE\PDBSEED\',
  'C:\APP\DELL\PRODUCT\21C\ORADATA\XE\mon_27976_denyse_ertriage_db\'
);

ALTER PLUGGABLE DATABASE mon_27976_denyse_ertriage_db OPEN;
ALTER PLUGGABLE DATABASE mon_27976_denyse_ertriage_db SAVE STATE;

ALTER SESSION SET CONTAINER = mon_27976_denyse_ertriage_db;

CREATE TABLESPACE er_data_tbs
  DATAFILE 'C:\APP\DELL\PRODUCT\21C\ORADATA\XE\mon_27976_denyse_ertriage_db\er_data01.dbf'
  SIZE 500M AUTOEXTEND ON NEXT 50M MAXSIZE 2G
  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE er_index_tbs
  DATAFILE 'C:\APP\DELL\PRODUCT\21C\ORADATA\XE\mon_27976_denyse_ertriage_db\er_index01.dbf'
  SIZE 200M AUTOEXTEND ON NEXT 20M MAXSIZE 1G
  EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TEMPORARY TABLESPACE er_temp_tbs
  TEMPFILE 'C:\APP\DELL\PRODUCT\21C\ORADATA\XE\mon_27976_denyse_ertriage_db\er_temp01.dbf'
  SIZE 200M AUTOEXTEND ON NEXT 20M MAXSIZE 1G;

ALTER USER DENYSE_ADMIN
  DEFAULT TABLESPACE er_data_tbs
  TEMPORARY TABLESPACE er_temp_tbs
  QUOTA UNLIMITED ON er_data_tbs;

GRANT DBA TO DENYSE_ADMIN;
