BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE medications_administered CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE treatment_sessions CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE er_meds CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE supply_inventory CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE supplies CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE critical_alerts CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE er_beds CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE medical_equipments CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE er_arrivals CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE shifts CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE medical_staffs CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE triage_levels CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE patients CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- PATIENTS
CREATE TABLE patients (
  patient_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
  national_id       VARCHAR2(20),
  first_name        VARCHAR2(50)      NOT NULL,
  last_name         VARCHAR2(50)      NOT NULL,
  date_of_birth     DATE              NOT NULL,
  gender            VARCHAR2(10)      CHECK (gender IN ('Male','Female','Other')),
  phone_number      VARCHAR2(20),
  email             VARCHAR2(100),
  address_line1     VARCHAR2(100),
  address_line2     VARCHAR2(100),
  city              VARCHAR2(50),
  state_province    VARCHAR2(50),
  postal_code       VARCHAR2(20),
  created_at        DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_patients PRIMARY KEY (patient_id),
  CONSTRAINT uq_patients_national_id UNIQUE (national_id)
) TABLESPACE er_data_tbs;

CREATE INDEX idx_patients_last_name ON patients(last_name) TABLESPACE er_index_tbs;

-- TRIAGE_LEVELS
CREATE TABLE triage_levels (
  triage_level_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
  level_code        NUMBER(1)        NOT NULL CHECK (level_code BETWEEN 1 AND 5),
  level_name        VARCHAR2(50)     NOT NULL,
  description       VARCHAR2(200),
  target_wait_mins  NUMBER(4),
  CONSTRAINT pk_triage_levels PRIMARY KEY (triage_level_id),
  CONSTRAINT uq_triage_levels_code UNIQUE (level_code)
) TABLESPACE er_data_tbs;

-- MEDICAL_STAFFS
CREATE TABLE medical_staffs (
  staff_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
  staff_number      VARCHAR2(20)     NOT NULL,
  first_name        VARCHAR2(50)     NOT NULL,
  last_name         VARCHAR2(50)     NOT NULL,
  role              VARCHAR2(30)     NOT NULL CHECK (role IN ('Triage Nurse','ER Physician','Bed Manager','Support Staff')),
  department        VARCHAR2(50),
  phone_number      VARCHAR2(20),
  email             VARCHAR2(100),
  active_flag       CHAR(1) DEFAULT 'Y' CHECK (active_flag IN ('Y','N')),
  CONSTRAINT pk_medical_staffs PRIMARY KEY (staff_id),
  CONSTRAINT uq_medical_staffs_number UNIQUE (staff_number)
) TABLESPACE er_data_tbs;

CREATE INDEX idx_medical_staffs_role ON medical_staffs(role) TABLESPACE er_index_tbs;

-- SHIFTS
CREATE TABLE shifts (
  shift_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
  staff_id          NUMBER            NOT NULL,
  shift_start       DATE              NOT NULL,
  shift_end         DATE              NOT NULL,
  shift_type        VARCHAR2(20)      CHECK (shift_type IN ('Day','Evening','Night')),
  CONSTRAINT pk_shifts PRIMARY KEY (shift_id),
  CONSTRAINT fk_shifts_staff FOREIGN KEY (staff_id)
    REFERENCES medical_staffs(staff_id)
) TABLESPACE er_data_tbs;

CREATE INDEX idx_shifts_staff ON shifts(staff_id) TABLESPACE er_index_tbs;

-- ER_BEDS
CREATE TABLE er_beds (
  bed_id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  bed_code          VARCHAR2(20)     NOT NULL,
  location_zone     VARCHAR2(30)     NOT NULL,
  is_isolation      CHAR(1) DEFAULT 'N' CHECK (is_isolation IN ('Y','N')),
  status            VARCHAR2(20) DEFAULT 'Available' CHECK (status IN ('Available','Occupied','Cleaning','OutOfService')),
  CONSTRAINT pk_er_beds PRIMARY KEY (bed_id),
  CONSTRAINT uq_er_beds_code UNIQUE (bed_code)
) TABLESPACE er_data_tbs;

-- MEDICAL_EQUIPMENTS
CREATE TABLE medical_equipments (
  equipment_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
  equipment_code    VARCHAR2(30)     NOT NULL,
  name              VARCHAR2(100)    NOT NULL,
  status            VARCHAR2(20) DEFAULT 'Available' CHECK (status IN ('Available','InUse','Maintenance','OutOfService')),
  location_zone     VARCHAR2(30),
  CONSTRAINT pk_medical_equipments PRIMARY KEY (equipment_id),
  CONSTRAINT uq_medical_equipments_code UNIQUE (equipment_code)
) TABLESPACE er_data_tbs;

-- ER_ARRIVALS
CREATE TABLE er_arrivals (
  arrival_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
  patient_id        NUMBER           NOT NULL,
  arrival_datetime  DATE             NOT NULL,
  arrival_mode      VARCHAR2(20)     NOT NULL CHECK (arrival_mode IN ('Walk-in','Ambulance','Transfer')),
  triage_level_id   NUMBER,
  triage_nurse_id   NUMBER,
  bed_id            NUMBER,
  physician_id      NUMBER,
  status            VARCHAR2(20) DEFAULT 'Waiting' CHECK (status IN ('Waiting','InTreatment','Discharged','Admitted','LeftWithoutBeingSeen','Deceased')),
  CONSTRAINT pk_er_arrivals PRIMARY KEY (arrival_id),
  CONSTRAINT fk_arrivals_patient FOREIGN KEY (patient_id)
    REFERENCES patients(patient_id),
  CONSTRAINT fk_arrivals_triage_level FOREIGN KEY (triage_level_id)
    REFERENCES triage_levels(triage_level_id),
  CONSTRAINT fk_arrivals_triage_nurse FOREIGN KEY (triage_nurse_id)
    REFERENCES medical_staffs(staff_id),
  CONSTRAINT fk_arrivals_bed FOREIGN KEY (bed_id)
    REFERENCES er_beds(bed_id),
  CONSTRAINT fk_arrivals_physician FOREIGN KEY (physician_id)
    REFERENCES medical_staffs(staff_id)
) TABLESPACE er_data_tbs;

CREATE INDEX idx_arrivals_patient ON er_arrivals(patient_id) TABLESPACE er_index_tbs;
CREATE INDEX idx_arrivals_triage_level ON er_arrivals(triage_level_id) TABLESPACE er_index_tbs;

-- ER_MEDS (medication catalog for ER)
CREATE TABLE er_meds (
  med_id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  med_code          VARCHAR2(30)     NOT NULL,
  generic_name      VARCHAR2(100)    NOT NULL,
  route             VARCHAR2(20)     CHECK (route IN ('IV','IM','PO','Subcut','Inhalation')),
  default_dose_mg   NUMBER(8,2),
  CONSTRAINT pk_er_meds PRIMARY KEY (med_id),
  CONSTRAINT uq_er_meds_code UNIQUE (med_code)
) TABLESPACE er_data_tbs;

-- TREATMENT_SESSIONS
CREATE TABLE treatment_sessions (
  session_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
  arrival_id        NUMBER           NOT NULL,
  start_time        DATE             NOT NULL,
  end_time          DATE,
  primary_diagnosis VARCHAR2(200),
  disposition       VARCHAR2(30)     CHECK (disposition IN ('Discharged','Admitted','Transferred','Deceased','LeftAgainstAdvice')),
  physician_id      NUMBER,
  CONSTRAINT pk_treatment_sessions PRIMARY KEY (session_id),
  CONSTRAINT fk_sessions_arrival FOREIGN KEY (arrival_id)
    REFERENCES er_arrivals(arrival_id),
  CONSTRAINT fk_sessions_physician FOREIGN KEY (physician_id)
    REFERENCES medical_staffs(staff_id)
) TABLESPACE er_data_tbs;

CREATE INDEX idx_sessions_arrival ON treatment_sessions(arrival_id) TABLESPACE er_index_tbs;

-- MEDICATIONS_ADMINISTERED
CREATE TABLE medications_administered (
  admin_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
  session_id        NUMBER           NOT NULL,
  med_id            NUMBER           NOT NULL,
  administered_time DATE             NOT NULL,
  dose_mg           NUMBER(8,2)      NOT NULL CHECK (dose_mg > 0),
  administered_by   NUMBER,
  CONSTRAINT pk_medications_administered PRIMARY KEY (admin_id),
  CONSTRAINT fk_meds_session FOREIGN KEY (session_id)
    REFERENCES treatment_sessions(session_id),
  CONSTRAINT fk_meds_med FOREIGN KEY (med_id)
    REFERENCES er_meds(med_id),
  CONSTRAINT fk_meds_staff FOREIGN KEY (administered_by)
    REFERENCES medical_staffs(staff_id)
) TABLESPACE er_data_tbs;

CREATE INDEX idx_meds_session ON medications_administered(session_id) TABLESPACE er_index_tbs;

-- SUPPLIES
CREATE TABLE supplies (
  supply_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
  supply_code       VARCHAR2(30)     NOT NULL,
  name              VARCHAR2(100)    NOT NULL,
  unit_of_measure   VARCHAR2(20),
  CONSTRAINT pk_supplies PRIMARY KEY (supply_id),
  CONSTRAINT uq_supplies_code UNIQUE (supply_code)
) TABLESPACE er_data_tbs;

-- SUPPLY_INVENTORY
CREATE TABLE supply_inventory (
  inventory_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
  supply_id         NUMBER           NOT NULL,
  location_zone     VARCHAR2(30)     NOT NULL,
  quantity_on_hand  NUMBER(10)       NOT NULL CHECK (quantity_on_hand >= 0),
  reorder_level     NUMBER(10)       CHECK (reorder_level >= 0),
  last_updated      DATE DEFAULT SYSDATE,
  CONSTRAINT pk_supply_inventory PRIMARY KEY (inventory_id),
  CONSTRAINT fk_inventory_supply FOREIGN KEY (supply_id)
    REFERENCES supplies(supply_id)
) TABLESPACE er_data_tbs;

-- CRITICAL_ALERTS
CREATE TABLE critical_alerts (
  alert_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
  arrival_id        NUMBER           NOT NULL,
  created_time      DATE DEFAULT SYSDATE NOT NULL,
  alert_type        VARCHAR2(50)     NOT NULL,
  severity          VARCHAR2(10)     CHECK (severity IN ('Low','Medium','High','Critical')),
  message           VARCHAR2(400),
  acknowledged_by   NUMBER,
  acknowledged_time DATE,
  CONSTRAINT pk_critical_alerts PRIMARY KEY (alert_id),
  CONSTRAINT fk_alerts_arrival FOREIGN KEY (arrival_id)
    REFERENCES er_arrivals(arrival_id),
  CONSTRAINT fk_alerts_staff FOREIGN KEY (acknowledged_by)
    REFERENCES medical_staffs(staff_id)
) TABLESPACE er_data_tbs;


