-- Phase VII Step 1: Create Holiday Management Table
CREATE TABLE public_holidays (
    holiday_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_date DATE NOT NULL UNIQUE,
    holiday_name VARCHAR2(100) NOT NULL,
    created_date DATE DEFAULT SYSDATE
) TABLESPACE er_data_tbs;

CREATE INDEX idx_holiday_date ON public_holidays(holiday_date) TABLESPACE er_index_tbs;

INSERT INTO public_holidays (holiday_date, holiday_name) VALUES (DATE '2025-12-25', 'Christmas Day');
INSERT INTO public_holidays (holiday_date, holiday_name) VALUES (DATE '2025-12-26', 'Boxing Day');
INSERT INTO public_holidays (holiday_date, holiday_name) VALUES (DATE '2026-01-01', 'New Year Day');

COMMIT;

-- Verify
SELECT * FROM public_holidays;