-- Phase VI Step 1: Create Audit and Error Log Tables
-- Run this first
CREATE TABLE er_audit_log (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_time DATE DEFAULT SYSDATE NOT NULL,
    action VARCHAR2(50) NOT NULL,
    arrival_id NUMBER,
    session_id NUMBER,
    old_status VARCHAR2(20),
    new_status VARCHAR2(20),
    user_name VARCHAR2(50),
    details VARCHAR2(4000)
) TABLESPACE er_data_tbs;

CREATE INDEX idx_audit_arrival ON er_audit_log(arrival_id) TABLESPACE er_index_tbs;

CREATE TABLE er_error_log (
    error_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_time DATE DEFAULT SYSDATE NOT NULL,
    procedure_name VARCHAR2(100),
    error_code NUMBER,
    error_message VARCHAR2(4000),
    extra_info VARCHAR2(4000)
) TABLESPACE er_data_tbs;

CREATE INDEX idx_error_log_time ON er_error_log(log_time) TABLESPACE er_index_tbs;

SELECT
    'Audit and error tables created successfully' AS status
FROM
    dual;